@startuml
/'Aluno: Henrique Paini/'
/'Caso de uso Delicias Gourmet
'/

left to right direction

 package Delicias_Gourmet{

package Funções {
  package Funcionarios {
  
  actor Gerente as Ger
  actor Supervisora as Su
  actor CoordenadorDeProdução as Coo
  actor Analista as AQ
  actor ResponsavelDasVendas as RVD
  
}
  package Função_Comprar {
   
    usecase "Registrar itens com compras a serem feitas" as UC14
    usecase "Compras em andamento e concluída" as UC15
    usecase "Registrar datas e previsão de chegada dos itens a emmpresa" as UC16
    usecase "Calcular valores de compra e negociação" as UC17
    usecase "Consultar estoque e utilização dos itens" as UC18
    usecase "Comprar" as UC3
  }
  package Funções_variadas{
  usecase "Verificar a necessidades de compra" as UC1
  usecase "Gerenciar processos de produção" as UC8
  usecase "Planejamento de organização da produção" as UC6
  usecase "Supervisionar" as UC4
  usecase "Supervisionar a produção" as UC7
  usecase "Desenvolver e implementar" as UC9
  usecase "Fazer avaliações de Qualidade" as UC10
  usecase "Fazer vendas e distribuições" as UC11
  usecase "Cuidar do estoque" as UC5
  usecase "Administrar recursos" as UC12
  usecase "Negociar valores" as UC2
  usecase "Administrar a distribuição de produtos" as UC13
}
}
  UC14 <|-- UC3 
  UC15 <|-- UC14
  UC16 <|-- UC15
  UC17 <|-- UC16
  UC18 <|-- UC17
  (Ger)--(UC1)
  (Ger)--(UC2)
  (Ger)--(UC3)
  (Su)--(UC4)
  (Su)--(UC5)
  (Coo)--(UC6)
  (Coo)--(UC7)
  (Coo)--(UC8)
  (AQ) -- (UC9)
  (AQ) -- (UC10)
  (RVD) -- (UC11)
  (RVD) -- (UC12)
  (RVD) -- (UC13)
  

}


RVD <|-- AQ
AQ <|-- Coo
Coo <|-- Su
Su <|-- Ger
@enduml
